//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthPlanPortal.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HealthPlanDBEntities : DbContext
    {
        public HealthPlanDBEntities()
            : base("name=HealthPlanDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Deductible> Deductibles { get; set; }
        public virtual DbSet<HealthPlan> HealthPlans { get; set; }
        public virtual DbSet<MajorMedical> MajorMedicals { get; set; }
        public virtual DbSet<Organization> Organizations { get; set; }
        public virtual DbSet<PreventiveCare> PreventiveCares { get; set; }
        public virtual DbSet<LoginUser> LoginUsers { get; set; }
    }
}
