//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthPlanPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HealthPlan
    {
        public int HealthPlanId { get; set; }
        public string HealthPlanCode { get; set; }
        public string HealthPlanDescription { get; set; }
        public string DeductibleId { get; set; }
        public string PreventiveCareId { get; set; }
        public string MajorMedicalId { get; set; }
        public Nullable<bool> PCPrequiredBool { get; set; }
        public Nullable<bool> PCPNetworkBool { get; set; }
    
        public virtual Deductible Deductible { get; set; }
        public virtual MajorMedical MajorMedical { get; set; }
        public virtual PreventiveCare PreventiveCare { get; set; }
    }
}
