//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthPlanPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HealthPlanDetail
    {
        public int HealthPlanDetailsId { get; set; }
        public int HealthPlanId { get; set; }
        public int DeductibleId { get; set; }
        public Nullable<int> PreventiveCareId { get; set; }
        public Nullable<int> MajorMedicalId { get; set; }
    
        public virtual Deductible Deductible { get; set; }
        public virtual HealthPlan HealthPlan { get; set; }
        public virtual MajorMedical MajorMedical { get; set; }
        public virtual PreventiveCare PreventiveCare { get; set; }
    }
}
