//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthPlanPortal.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Deductible
    {
        public int DeductibleId { get; set; }
        [Display(Name = "Health Plan Type")]
        public int HealthPlanId { get; set; }
        [Display(Name = "Deductible Code")]
        public string DeductibleCode { get; set; }
        [Display(Name = "Individual Deductible amount")]
        public Nullable<decimal> IndividualDedAmt { get; set; }
        [Display(Name = "Family Deductible Amount")]
        public Nullable<decimal> FamilyDedAmt { get; set; }
        [Display(Name = "Max Deductible Amount Per Individual")]
        public Nullable<decimal> MaxDeductibleAmountPerIndividual { get; set; }
        [Display(Name = "Any Services Covered Before the deductibles met?")]
        public Nullable<bool> ServicesCoveredBeforeDeductibleMetBool { get; set; }
        [Display(Name = "Is the deductible Included in Out of packet?")]
        public Nullable<bool> DeductibleIncdInOutOfPcktBool { get; set; }
        [Display(Name = "Does the plans have annual Limits?")]
        public Nullable<bool> AnnualLimitsPlanBool { get; set; }
        [Display(Name = "If So what is the annual Limit?")]
        public Nullable<decimal> AnnualPremium { get; set; }
        [Display(Name = "Coinsurance Upper Limit?")]
        public Nullable<decimal> CoinsuranceUpper { get; set; }
        [Display(Name = "Coinsurance Lower Limit?")]
        public Nullable<decimal> CoinsuranceLower { get; set; }
        [Display(Name = "Annual Limit Higher?")]
        public Nullable<decimal> AnnualLimitHigher { get; set; }
        [Display(Name = "Annual Limit Lower?")]
        public Nullable<decimal> AnnualLimitLower { get; set; }
        [Display(Name = "Total Estimated Cost?")]
        public Nullable<decimal> TotalEstimatedCost { get; set; }        
        public virtual HealthPlan HealthPlan { get; set; }
    }
}
