//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthPlanPortal.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class MajorMedical
    {
        public int MajorMedicalId { get; set; }
        [Display(Name = "Do you have copy of the Plans Provider list?")]
        public Nullable<bool> MajorMedicalProvideListBool { get; set; }
        [Display(Name = "MajorMedical Description")]
        public string MajorMedicalDescription { get; set; }
        [Display(Name = "Health Plan Type")]
        public Nullable<int> HealthPlanId { get; set; }
    
        public virtual HealthPlan HealthPlan { get; set; }
    }
}
