//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthPlanPortal.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Organization
    {
        [Display(Name = "ID")]
        public int OrganizationId { get; set; }
        [Display(Name = "Code")]
        public string OrganizationCode { get; set; }
        [Display(Name = "Name")]
        public string OrganizationName { get; set; }
        [Display(Name = "Description")]
        public string OrganizationDescription { get; set; }
        [Display(Name = "Phone Number")]
        public string OrganizationPhoneNumber { get; set; }
        [Display(Name = "Email Address")]
        public string OrganizationEmailAddress { get; set; }
        [Display(Name = "Address")]
        public string OrganizationAddress { get; set; }
        [Display(Name = "City")]
        public string OrganizationCity { get; set; }
        [Display(Name = "State")]
        public string OrganizationState { get; set; }
        [Display(Name = "zip")]
        public string OrganizationZip { get; set; }
    }
}
