//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrganizationPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Address()
        {
            this.Employees = new HashSet<Employee>();
            this.PrimaryCareProviders = new HashSet<PrimaryCareProvider>();
        }
    
        public string AddressId { get; set; }
        public string Address_Street1 { get; set; }
        public string Address_Street2 { get; set; }
        public string Address_City { get; set; }
        public string Address_State { get; set; }
        public string Address_Zip { get; set; }
        public string Address_Country { get; set; }
        public string Address_Email { get; set; }
        public string Address_Home_Phone { get; set; }
        public string Address_Work_Phone { get; set; }
        public string Address_Cell_phone { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee> Employees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrimaryCareProvider> PrimaryCareProviders { get; set; }
    }
}
