//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrganizationPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.EmployeePolicies = new HashSet<EmployeePolicy>();
        }
    
        public string EmployeeId { get; set; }
        public string Employee_First_Name { get; set; }
        public string Employee_Last_Name { get; set; }
        public string Employee_Middle_Name { get; set; }
        public string Employee_SSN { get; set; }
        public Nullable<System.DateTime> Employee_DOB { get; set; }
        public string Eomployee_Gender { get; set; }
        public string Employee_Address_Id { get; set; }
        public string Marital_Status_id { get; set; }
        public string Coverage_Id { get; set; }
        public string Primary_Care_Id { get; set; }
        public string PCP { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Coverage Coverage { get; set; }
        public virtual MaritalStatu MaritalStatu { get; set; }
        public virtual PrimaryCareProvider PrimaryCareProvider { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeePolicy> EmployeePolicies { get; set; }
    }
}
