//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrganizationPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrimaryCareProvider
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PrimaryCareProvider()
        {
            this.Employees = new HashSet<Employee>();
        }
    
        public string PrimaryCareProviderId { get; set; }
        public string PrimaryCareProviderFirstName { get; set; }
        public string PrimaryCareProviderLastName { get; set; }
        public string PrimaryCareProviderAddressId { get; set; }
    
        public virtual Address Address { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee> Employees { get; set; }
    }
}
